spring:
  application:
    name: CarManagementSystem
  datasource:
    url: jdbc:mysql://localhost:3306/car_management_db?createDatabaseIfNotExist=true
    username: root
    password: Inventabilii14
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
